openapi: 3.0.0
info:
  title: TruthTok API
  description: API for the TruthTok video platform
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Development server
  - url: https://api.truthtok.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Video:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
        userId:
          type: string
          format: uuid
        location:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          enum: [PENDING, PROCESSING, PROCESSED, COMPLETED, ERROR, FAILED]
        description:
          type: string
        aiDescription:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    VideoMetadata:
      type: object
      properties:
        duration:
          type: number
        format:
          type: string
        size:
          type: integer
        width:
          type: integer
        height:
          type: integer
        fps:
          type: number
        codec:
          type: string
        bitrate:
          type: integer

    Caption:
      type: object
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        startTime:
          type: number
        endTime:
          type: number

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

paths:
  /videos:
    post:
      summary: Upload a new video
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                location:
                  type: object
                  properties:
                    lat:
                      type: number
                    lng:
                      type: number
      responses:
        '201':
          description: Video uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List videos
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, PROCESSING, PROCESSED, COMPLETED, ERROR, FAILED]
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer

  /videos/{id}:
    get:
      summary: Get video details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Video details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '404':
          description: Video not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /videos/{id}/metadata:
    get:
      summary: Get video metadata
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Video metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoMetadata'

  /videos/{id}/captions:
    get:
      summary: Get video captions
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Video captions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Caption'

  /clusters:
    get:
      summary: Get video clusters
      security:
        - bearerAuth: []
      parameters:
        - name: lat
          in: query
          schema:
            type: number
        - name: lng
          in: query
          schema:
            type: number
        - name: radius
          in: query
          schema:
            type: number
        - name: startTime
          in: query
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of video clusters
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    centerLocation:
                      type: object
                      properties:
                        lat:
                          type: number
                        lng:
                          type: number
                    radiusKm:
                      type: number
                    timeStart:
                      type: string
                      format: date-time
                    timeEnd:
                      type: string
                      format: date-time
                    story:
                      type: string
                    videos:
                      type: array
                      items:
                        $ref: '#/components/schemas/Video'
